import { Button, Footer, Form, Layout, Table } from '@src/components';
import { Client } from '@src/core';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import Axios from 'axios';

const Home: NextPage = () => {
  const [list, setList] = useState();
  const [client, setClient] = useState<Client>(Client.empty());
  const [focus, setFocus] = useState<'table' | 'form'>('table');

  useEffect(() => {
    Axios.get('http://localhost:5000/db').then((response) => {
    setList(response.data);
    });
  });

  const clientSelectedFocus = (clientSelected: Client) => {
    setClient(clientSelected);
    setFocus('form');
  };

  const clientDeletedFocus = (clientSelected: Client) => {
    Axios.post('http://localhost:5000/delete', {
      id: clientSelected.idclients
    }).then((response) => {
      Axios.get('http://localhost:5000/db').then((resp) => {
      setList(resp.data);
      });
    });
  };

  const newClient = () => {
    setClient(Client.empty());
    setFocus('form');
  };

  const saveClient = (clientChange: Client) => {
    console.log(clientChange);
    Axios.post('http://localhost:5000/saveorupdate', {
      name: clientChange.name,
      age: clientChange.age,
      id: clientChange.idclients
    }).then((response) => {
      setList(response.data);
    });
    setFocus('table');
  };

  return (
    <>
      <Head>
        <title>CRUD</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div>
        <Layout title='Cadastro simples'>
          {focus === 'table' ? (
            <>
              <div className='divButton'>
                <Button onClick={newClient} >Novo Cliente</Button>
              </div>
              <Table
                clients={list} /*Aqui ficava o clientsInput*/
                clientSelect={clientSelectedFocus}
                clientDeleted={clientDeletedFocus}
              />
            </>
          ) : (
            <Form client={client} onChange={saveClient} cancel={() => setFocus('table')} />
          )}
        </Layout>
      </div>

      <Footer>
        <p>Todos os direitos reservados.</p>
      </Footer>
    </>
  );
};

export default Home;
